local wezterm = require("wezterm")

return {
	default_prog = { "/usr/local/bin/fish" },
	check_for_updates = true,
	default_cursor_style = "SteadyBar",
	cursor_thickness = 2,
	initial_cols = 130,
	initial_rows = 25,
	-- font = wezterm.font("MesloLGLDZ Nerd Font"),
	font = wezterm.font("JetBrainsMono Nerd Font", { weight = "ExtraLight" }),
	-- font = wezterm.font("Iosevka Nerd Font Mono"),
	font_size = 15,
	freetype_load_target = "Light",
	freetype_render_target = "HorizontalLcd",
	line_height = 1.3,
	bold_brightens_ansi_colors = true,
	-- dpi = 144.0,
	-- color_scheme = "Aci (Gogh)",
	color_scheme = "TokyoNightStorm (Gogh)",
	-- color_scheme = "tokyonight",
	-- color_scheme = "Github Dark",
	-- color_scheme = "ayu",
	hide_tab_bar_if_only_one_tab = true,
	colors = {
		background = "#0f1119",
		-- background = "#151f32",
	},
	window_decorations = "RESIZE",
	window_padding = {
		left = 22,
		right = 22,
		bottom = 22,
		top = 36,
	},
	window_frame = {
		font_size = 14,
		inactive_titlebar_bg = "#353535",
		active_titlebar_bg = "#2b2042",
		inactive_titlebar_fg = "#cccccc",
		active_titlebar_fg = "#ffffff",
		inactive_titlebar_border_bottom = "#2b2042",
		active_titlebar_border_bottom = "#2b2042",
		button_fg = "#cccccc",
		button_bg = "#2b2042",
		button_hover_fg = "#ffffff",
		button_hover_bg = "#3b3052",

		-- active_titlebar_bg = "rgb(25, 26, 42)",
	},
}
