#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.vim $HOME/.vimrc
ln -s $DOTFILES/vim/vim $HOME/.vim
ln -s $DOTFILES/vim/vimrc $HOME/.vimrc

# rm -rf $HOME/.config/nvim
# ln -s $DOTFILES/nvim $HOME/.config/nvim
rm -rf $HOME/.config/nvim/lua/custom
ln -s $DOTFILES/nvchad/custom $HOME/.config/nvim/lua/custom

rm -rf $HOME/.config/lvim
ln -s $DOTFILES/lvim $HOME/.config/lvim
