set nocompatible																"We want the latest Vim settings/options.

"Load Plugins from file
so ~/.vim/plugins.vim


syntax enable
set backspace=indent,eol,start									"Make BackSpace behave like every other editor
let mapleader = ','															"Change Default Leader from \ to ,
set number																			"Activate line numbers


"-----------Visuals------------"
set background=dark
set termguicolors

" Ayu theme color settings
let ayucolor="dark"
colorscheme ayu

set t_CO=256																		"Set Terminal Colors
"set guifont=Fira_Code:h17											"Set Font and Size
set guifont=JetBrains_Mono_Slashed:h16
set linespace=12																"Set GUI line height

set guioptions -=l
set guioptions -=L
set guioptions -=r
set guioptions -=R

"-----------Searching------------"
set hlsearch
set incsearch



"-----------Mappings------------"
set splitbelow
set splitright

nmap <C-J> <C-W><C-J>
nmap <C-K> <C-W><C-K>
nmap <C-H> <C-W><C-H>
nmap <C-L> <C-W><C-L>


"-----------Mappings------------"
"Make it easy to edit Vimrc
nmap <Leader>ev :tabedit ~/.vimrc<cr>

"Add simple highlight removal
nmap <Leader><space> :nohlsearch<cr>

"Make NerdTree easier to toggle
nmap <D-1> :NERDTreeToggle<cr>

"Close All Buffers
nmap <Leader>ca :bufdo bd!<cr>

"CTRL-p stuff
nmap <c-R> :CtrlPBufTag<cr>
nmap <D-e> :CtrlPMRUFiles<cr>


"-----------Plugins--------"
let g:ctrlp_custom_ignore = 'node_modules\DS_Store\vendor\|git'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:30,results:30'

let g:ale_fixers = { 'javascript': ['eslint'] }											"ESLint Setup
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '⚠️'
let g:ale_fix_on_save = 1

"Must be loaded before the plugin initialized
let g:ale_completion_enabled = 1

"-----------Auto-Command--------"
"Automatically Source the Vimrc file on save.
augroup autosourcing
	autocmd!
	autocmd BufWritePost .vimrc source %
augroup END
